# FILE: ./docker-compose.yml

networks:
  robopost_network:
    driver: bridge

volumes:
  mysql_data:
  rabbitmq_data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - robopost_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    networks:
      - robopost_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  management-api:
    build:
      context: ./services/management-api
      dockerfile: Dockerfile
    container_name: management-api
    env_file: .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./services/management-api:/usr/src/app
      - ./common:/usr/src/app/common
    networks:
      - robopost_network
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # --- START: این بخش کلیدی مشکل را حل می‌کند ---
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 30s
    # --- END: بخش اضافه شده ---

  fetcher-service:
    build:
      context: ./services/fetcher-service
      dockerfile: Dockerfile
    container_name: fetcher-service
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./services/fetcher-service/app:/usr/src/app/app
      - ./common:/usr/src/app/common
    environment:
      - PYTHONPATH=/usr/src/app
    networks:
      - robopost_network
    depends_on:
      management-api:
        # --- START: این بخش مشکل را حل می‌کند ---
        condition: service_healthy
        # --- END: بخش اصلاح شده ---

  publisher-service:
    build:
      context: ./services/publisher-service
      dockerfile: Dockerfile
    container_name: publisher-service
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./services/publisher-service/app:/usr/src/app/app
      - ./common:/usr/src/app/common
    environment:
      - PYTHONPATH=/usr/src/app
    networks:
      - robopost_network
    depends_on:
      management-api:
        # --- START: این بخش مشکل را حل می‌کند ---
        condition: service_healthy
        # --- END: بخش اصلاح شده ---
      rabbitmq:
        condition: service_healthy

  processor-service:
    build:
      context: ./services/processor-service
      dockerfile: Dockerfile
    container_name: processor-service
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./services/processor-service/app:/usr/src/app/app
      - ./common:/usr/src/app/common
    environment:
      - PYTHONPATH=/usr/src/app
    networks:
      - robopost_network
    depends_on:
      management-api:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  telegram-manager:
    build:
      context: ./services/telegram-manager
      dockerfile: Dockerfile
    container_name: telegram-manager
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./services/telegram-manager/app:/usr/src/app/app
      - ./common:/usr/src/app/common
    environment:
      - PYTHONPATH=/usr/src/app
    networks:
      - robopost_network
    depends_on:
      management-api:
        condition: service_healthy        